const postData = [
    {
        postCover: "post1.png",
        postCategory: "1",
        postTitle: "What if famous brands had regular fonts? Meet RegulaBrands!",
        postContent: " I’ve worked in UX for the better part of a decade. From now on, I plan to retrieve bla bla bla.",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
    {
        postCover: "post2.png",
        postCategory: "2",
        postTitle: "Tax Benefits for Investment under National Pension Scheme launched by Government",
        postContent: " I’ve worked in UX for the better part of a decade. From now on, I plan to retrieve bla bla bla.",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
    {
        postCover: "post3.png",
        postCategory: "3",
        postTitle: "What if famous brands had regular fonts? Meet RegulaBrands!",
        postContent: " I’ve worked in UX for the better part of a decade. From now on, I plan to retrieve bla bla bla.",
        date: "Fri, 12 Oct, 2018",
        location: "Ahmedabad, India",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
    {
        postCover: "",
        postCategory: "4",
        postTitle: "Software Developer",
        postContent: " Innovaccer Analytics Private Ltd.",
        location: "Noida, India",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
]

export default postData;