const postData = [
    {
        postCover: "post1.png",
        postIcon: "✍️",
        postCategory: "Article",
        postTitle: "What if famous brands had regular fonts? Meet RegulaBrands!",
        postContent: " I’ve worked in UX for the better part of a decade. From now on, I plan to retrieve bla bla bla.",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
    {
        postCover: "post2.png",
        postIcon: "🔬️",
        postCategory: "Education",
        postTitle: "Tax Benefits for Investment under National Pension Scheme launched by Government",
        postContent: " I’ve worked in UX for the better part of a decade. From now on, I plan to retrieve bla bla bla.",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
    {
        postCover: "post3.png",
        postIcon: "🗓️",
        postCategory: "Meetup",
        postTitle: "What if famous brands had regular fonts? Meet RegulaBrands!",
        postContent: " I’ve worked in UX for the better part of a decade. From now on, I plan to retrieve bla bla bla.",
        date: "today",
        time: "8 am",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
    {
        postCover: "",
        postIcon:"💼️",
        postCategory: "Job",
        postTitle: "Software Developer",
        postContent: " Innovaccer Analytics Private Ltd.",
        postUrl:"",
        redirectUrl: "",
        userImg: "",
        userName: "",
    },
]

export default postData;